version: '2.3'
services:

  cloudera-rstudio:
    hostname: quickstart.cloudera
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8888:8888
      - 7180:7180
      - 8080:80
      - 3306:3306
    tty: true
    privileged: true
    restart: always
    command: /usr/bin/docker-quickstart #/home/cloudera/cloudera-manager --express
